---
title: "Survival Analysis"
subtitle: "It's Uncertainty All the Way Down" # e.g. the occasion
author: "Lukas Burk" # For the title slide
date: "2021-07-02" # Automatically evaluates to today
output:
  xaringan::moon_reader:
    # css: [bips.css, default]
    css: [xaringan-themer.css, custom-sizing.css]
    lib_dir: js
    nature:
      beforeInit: macros.js
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%" # Only show current slide number
      ratio: "16:9" # Use "4:3" for old projectors etc.
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  dev = "ragg_png",
  fig.align = "center",
  fig.retina = 2,
  fig.height = 5,
  fig.width = 7
)

library(xaringanthemer)
style_mono_accent(
  base_color = "#006633",
  header_font_google = google_font("Lato"),
  text_font_google   = google_font("Source Sans Pro", "400", "400i"),
  code_font_google   = google_font("Fira Mono"),
  header_color = lighten_color("#006633", strength = .2),
  link_color = lighten_color("#006633", strength = .5),
  base_font_size = "25px",
  black_color = "#0A0A0A"
)

# xaringanExtra features, see https://pkg.garrickadenbuie.com/xaringanExtra/
xaringanExtra::use_xaringan_extra(
  c("tile_view", "panelset")
)
xaringanExtra::use_progress_bar(
  color = "red", location = "bottom", height = "10px"
)

library(survival)
library(survminer)
library(tidyverse)
library(kableExtra)

theme_local <- function(...) {
  theme_xaringan() +
  theme(
    axis.line = element_line(color = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    ...
  )
}

set.seed(1)
veteran <- veteran %>%
  mutate(id = row_number()) %>%
  tibble::remove_rownames() %>%
  slice_sample(prop = 1)
```

layout: true
## Survival Data

.pull-left[

```{r faux-survtbl}
veteran %>%
  group_by(status) %>%
  slice_head(n = 4) %>%
  ungroup() %>%
  arrange(id) %>%
  select(id, time, trt, age) %>%
  kable() %>%
  kable_styling() %>%
  column_spec(2, bold = TRUE)
```

]

---

--

- `time` looks like a continuous variable

--

- Seems fine ðŸ§

--

- That's because this is a lie ðŸ˜­


---
layout: true 
## Actual Survival Data

.pull-left[

```{r actual-survtbl}
veteran %>%
  group_by(status) %>%
  slice_head(n = 4) %>%
  arrange(id) %>%
  select(id, time, status, trt, age) %>%
  mutate(
    status = cell_spec(status, color = ifelse(status == 0, "red", "black"))
  ) %>%
  kable(escape = FALSE) %>%
  kable_styling() %>%
  column_spec(2, bold = TRUE) %>%
  column_spec(3, bold = TRUE)
```

]

---

--

```{r cumfplot}
veteran <- veteran %>%
  arrange(time) %>%
  mutate(
    Fhat = cumsum(time)/sum(time),
    Shat = 1 - Fhat
  )

veteran %>%
  ggplot(aes(x = time, y = Fhat)) +
  geom_step(size = 1.5) +
  labs(
    x = "Time",
    y = expression(hat(F)(t))
  ) +
  theme_local()
```

---

$$S(t) := 1 - F(t)$$

```{r survplot}
veteran %>%
  ggplot(aes(x = time, y = Shat)) +
  geom_step(size = 1.5) +
  labs(
    x = "Time",
    y = expression(hat(S)(t))
  ) +
  theme_local()
```

---

```{r survplot-full, fig.height = 9, fig.width = 9, out.width = "45%"}
veteranmod <- survfit(Surv(time, status) ~ trt, data = veteran)
ggsurvplot(
  veteranmod, 
  data = veteran,
  conf.int = TRUE,
  palette = "Dark2",
  ggtheme = theme_local(),
  surv.median.line = "hv",
  risk.table = "absolute"
)
```


---
layout: false
class: middle, center
## Estimating Hazards Instead

--

$$\begin{align}
\color{red}{\lambda(t)} &:= \lim_{\Delta t \to 0} \frac{\mathrm{Pr}(t \leq T < \Delta t\ |\ T \geq t)}{\Delta t}
\end{align}$$

--

![:vspace 5]

.pull-left[

Hazard gives us $S(t)$

$$S(t) = \exp\left(-\int_0^t \color{red}{\lambda(u)} \mathrm{d}u\right)$$

]

--

.pull-right[

...and also $f(t)$

$$
f(t) = \color{red}{\lambda(t)} \exp\left(-\int_0^t \color{red}{\lambda(u)} \mathrm{d}u\right)
$$
]
